CREATE TABLE PRODUCTS(
SKU_ID INTEGER NOT NULL,
SKUNAME VARCHAR(255) NOT NULL,
CATEGORY VARCHAR(255) NOT NULL,
BRAND VARCHAR(255),
COLOUR VARCHAR(255),
SIZE VARCHAR(255) NOT NULL,
PRICE DOUBLE,
PRIMARY KEY(SKU_ID)
);

CREATE TABLE SELLERS(
SELLER_ID INTEGER NOT NULL,
SELLERNAME VARCHAR(255) NOT NULL,
PRIMARY KEY(SELLER_ID)
);

CREATE TABLE PRODUCTS_SELLERS(
SELLER_ID INTEGER NOT NULL,
SKU_ID INTEGER NOT NULL,
NOOFPRODUCTS INTEGER,
FOREIGN KEY (SELLER_ID) REFERENCES SELLERS(SELLER_ID),
FOREIGN KEY (SKU_ID) REFERENCES PRODUCTS(SKU_ID)
);

